bungeeRandomMapPickOnStart: false
debugMode: false
bungeeMode: false
bungeeLobby: lobby
isLobbyServer: false
gameServers:
- server-name:port:display name:max players:team size
tauntCooldown: 10
enablePressurePlateJoin: true
teleportToSpawnOnJoin: false
teleportToSpawnOnWorldEnter: true
resourcepack: []
promptForResourcePackOnJoin: false
lobbyBoardEnabled: false
displayPlayerLevelOnXpBar: true
enabledLobbyGuard: false
economyEnabled: true
clearInventoryOnLobbyJoin: true
timeFormat: simplified
slimeworldmanager:
  enable: false
  source: file
game:
  win:
    clearInventory: true
    enableFlight: false
  kickOnWorldTeleport: true
  enableQuickDeath: true
  quickDeathY: -10
  enablePVPTimer: true
  PVPTimerTime: 10
  enableWinMessage: true
  enableLookDirection: true
  worldBorder:
    enabled: false
    borderSize: 400
  showHealth: true
  snowballDamage: 1
  eggDamage: 1
  ecoForWin: 10
  ecoForKill: 5
  xpForWin: 5
  winCommands: []
  xpForKill: 3
  killCommands: []
  vip1Multiplier: 2
  vip2Multiplier: 3
  vip3Multiplier: 4
  vip4Multiplier: 5
  vip5Multiplier: 10
  timeAfterMatch: 15
  waitTimer: 45
  resetTimerOnJoin: false
  kitVotingEnabled: false
  spectateEnabled: true
  maxMapSize: 400
  tauntsEnabled: true
  modifierLevel:
    strength: 0
    speed: 0
    jump: 0
  displayTimerOnLevelbar: false
teams:
  usePlayerNames: true
  usePlayerGlassColors: true
  useTeamNumberInMenu: true
  teamCageMaterial: GLASS
  useTeamMaterialBytes: false
  standardTeamMaterialByte: 4
  useSeparateCages: true
  changeTablistNames: true
chat:
  useTeamChat: true
  enableFormatter: false
  limitGameChatToGame: true
  limitLobbyChatToLobby: false
  limitSpecChatToSpec: true
  externalChat:
    useExternalChat: false
    addPrefix: false
parties:
  enabled: true
  enablePartyAndFriendsSupport: false
  maxPartySize: 4
  lobbyWorlds:
  - world_skywars
holograms:
  enabled: false
chests:
  loadTrappedChestsAsCenter: false
  maxItemsChest: 26
  maxItemsDoubleChest: 53
kit:
  menuSize: 45
  randPos: 0
  randItem: NETHER_STAR
  noKitPos: 44
  noKitItem: BARRIER
titles:
  enabled: true
fireworks:
  enabled: true
  per5Ticks: 1
sounds:
  teamJoinSound: BLOCK_NOTE_BLOCK_PLING
  enabled: true
  countdown: BLOCK_NOTE_BLOCK_BASS
  join: BLOCK_WOODEN_DOOR_OPEN
  leave: BLOCK_WOODEN_DOOR_CLOSE
  openJoinMenu: BLOCK_FENCE_GATE_OPEN
  openSpectateMenu: BLOCK_FENCE_GATE_OPEN
  openOptionsMenu: ENTITY_ZOMBIE_VILLAGER_CURE
  openGlassMenu: BLOCK_GLASS_BREAK
  openWinSoundMenu: ENTITY_FIREWORK_ROCKET_BLAST
  openKillSoundMenu: ENTITY_PIG_DEATH
  openParticleMenu: BLOCK_GRAVEL_STEP
  openProjectileMenu: ENTITY_ARROW_SHOOT
  openTauntMenu: ENTITY_ENDER_DRAGON_FLAP
  openKitMenu: ENTITY_PLAYER_ATTACK_SWEEP
  openChestMenu: BLOCK_CHEST_OPEN
  openHealthMenu: ENTITY_SPLASH_POTION_BREAK
  openTimeMenu: ITEM_BOTTLE_FILL_DRAGONBREATH
  openWeatherMenu: WEATHER_RAIN
  openModifierMenu: ENTITY_SPLASH_POTION_BREAK
  confirmSelectionSound: ENTITY_VILLAGER_YES
  errorSound: ENTITY_VILLAGER_NO
signs:
  enabled: true
  blockoffline: BLACK_CONCRETE
  blockwaiting: LIME_CONCRETE
  blockplaying: ORANGE_CONCRETE
  blockending: RED_TERRACOTTA
  almostfull: DIAMOND_HELMET
  threefull: GOLDEN_HELMET
  halffull: IRON_HELMET
  almostempty: LEATHER_HELMET
items:
  randomVoteEnabled: true
  scavengerChestEnabled: true
  joinGameItemEnabled: true
  spectateGameItemEnabled: true
  optionsItemEnabled: true
  teamSelectPosition: 2
  teamSelectItem: END_CRYSTAL
  kitsEnabled: true
  kitVotePosition: 0
  kitvote: ENDER_CHEST
  voteEnabled: true
  votingPosition: 4
  votingItem: PAPER
  exitGameItem: STRUCTURE_VOID
  exitPosition: 8
  exitMenuItem: STRUCTURE_VOID
  prevPageItem: ARROW
  nextPageItem: ARROW
  chestVoteEnabled: true
  chestVotePosition: 9
  chestvote: CHEST
  chestrandom: NETHER_STAR
  chestbasic: WOODEN_SWORD
  chestnormal: IRON_SWORD
  chestop: DIAMOND_SWORD
  chestscavenger: BARRIER
  healthVoteEnabled: true
  healthVotePosition: 11
  healthvote: EXPERIENCE_BOTTLE
  healthrandom: NETHER_STAR
  healthfive: APPLE
  healthten: GOLDEN_APPLE
  healthfifteen: ENCHANTED_GOLDEN_APPLE
  healthtwenty: TOTEM_OF_UNDYING
  nopermission: STRUCTURE_VOID
  timeVoteEnabled: true
  timeVotePosition: 13
  timevote: CLOCK
  timerandom: NETHER_STAR
  timedawn: CLOCK
  timenoon: CLOCK
  timedusk: CLOCK
  timemidnight: CLOCK
  weatherVoteEnabled: true
  weatherVotePosition: 15
  weathervote: WATER_BUCKET
  weatherrandom: NETHER_STAR
  weathersunny: SUNFLOWER
  weatherrain: WATER_BUCKET
  weatherstorm: PRISMARINE_SHARD
  weathersnow: SNOWBALL
  modifierVoteEnabled: true
  modifierVotePosition: 17
  modifiervote: DRAGON_BREATH
  modifierspeed: FEATHER
  modifierjump: SLIME_BLOCK
  modifierstrength: IRON_AXE
  modifiernone: BARRIER
  modifierrandom: NETHER_STAR
  joinselect: NETHER_STAR
  singleSlot: 11
  singlemenu: REDSTONE_TORCH
  teamSlot: 15
  teammenu: COMPARATOR
  spectateselect: ENDER_EYE
  optionselect: BOOK
  particleselect: BLAZE_POWDER
  particleselectslot: 11
  projectileselect: ARROW
  projectileselectslot: 12
  killsoundselect: DIAMOND_SWORD
  killsoundselectslot: 14
  killsounditem: NOTE_BLOCK
  winsoundselect: FIREWORK_ROCKET
  winsoundselectslot: 15
  glassselect: GLASS
  glassselectslot: 9
  tauntselect: PUFFERFISH
  tauntselectslot: 17
particles:
  enabled: true
  ticksperupdate: 3
enabledMenus:
  join: true
  joinSlot: 0
  spectate: true
  spectateSlot: 4
  options: true
  optionsSlot: 8
  glass: true
  particle: true
  projectile: true
  killsound: true
  winsound: true
  taunts: true
sqldatabase:
  enabled: false
  hostname: localhost
  port: 3306
  database: database
  username: username
  password: password
leaderboards:
  eloLeaderboardEnabled: true
  length: 10
  leaderboardUpdateInterval: 300
  signsEnabled: true
  headsEnabled: true
  winsLeaderboardEnabled: true
  lossesLeaderboardEnabled: true
  killsLeaderboardEnabled: true
  deathsLeaderboardEnabled: true
  xpLeaderboardEnabled: true
disable-commands:
  exceptions:
  - msg
  - r
  - sw quit
  enabled: true
disable-commands-spectate:
  exceptions:
  - msg
  - r
  - sw quit
  enabled: true
updater:
  checkForBetaVersions: false
spawn: world_skywars:0.5:30.0:0.5:90.14996:-26.250023
gameEndCommands: []
