# WELCOME TO THE OFFICIAL SLEEP-MOST PLUGIN
# AUTHORS: MrGeneralQ, HorrendousEntity
# CONTRIBUTORS: Nozemi, Malin
# VERSION: 5.0.1
# SUPPORT NEEDED? Join our discord at --> https://discord.pseudonova.com/ WE ARE HAPPY TO HELP YOU FURTHER!
# YOU CAN FIND THE DOCS FOR THIS PLUGIN HERE --> https://mrgeneralq.gitbook.io/sleepmost/
#
#
# WARNING: SUPPORT IS ONLY GIVEN TO THE LATEST VERSION
sleep:
  world:
    enabled: false
    calculation-method: percentage
    percentage-required: 0.5
    mob-no-target: true
    use-exempt: true
    use-afk: false
    prevent-sleep: false
    prevent-phantom: false
    nightcycle-animation: true
    storm-sleep: true
    skip-storm: true
    clock-animation: true
    allow-sleep-cmd: false
    exempt-below-y: -1
    non-sleeping-sound: false
    non-sleeping-title: false
    exempt-flying: false
    non-sleeping-clock-animation: false
    insomnia-chance: 0.0
    phantom-reset-audience: all
    allow-kick: false
    gsit-sleep: true
    dynamic-animation-speed: false
    insomnia-milk: false
    longer-night-duration: 0
    gsit-hook: false
    disable-daylight-cycle-gamerule: true
  world2:
    enabled: false
    percentage-required: 0.5
    mob-no-target: true
    use-exempt: false
    use-afk: false
    prevent-sleep: false
    prevent-phantom: false
    nightcycle-animation: false
    storm-sleep: true
  tiendas:
    enabled: false
    calculation-method: percentage
    percentage-required: 0.5
    players-required: 5
    mob-no-target: true
    use-exempt: true
    use-afk: false
    prevent-sleep: false
    prevent-phantom: false
    nightcycle-animation: false
    storm-sleep: false
    skip-delay: 0
    heal: false
    feed: false
    non-sleeping-clock-animation: false
    insomnia-chance: 0.0
    skip-storm: true
    use-bossbar: false
    exempt-flying: false
    exempt-creative: false
    exempt-spectator: false
    non-sleeping-sound: false
    use-title-night-skipped: false
    use-sound-night-skipped: false
    use-title-storm-skipped: false
    exempt-below-y: -1
    use-sound-storm-skipped: false
    clock-animation: true
    skip-storm-sound: entity.wither.spawn
    allow-sleep-cmd: true
    allow-kick: false
    phantom-reset-audience: all
    skip-night-sound: ui.toast.challenge_complete
    non-sleeping-title: false
time-after-reset: 0
messages:
  prefix: ''
  cooldown: 10
  night-skipped: ''
  storm-skipped: ''
  players-left-night: '&bJugadores necesarios para pasar la noche: &e%sleeping%&b/&e%required%'
  players-left-storm: '&bJugadores necesarios para pasar la tormenta: &e%sleeping%&b/&e%required%'
  sleep-prevented: '&cNo puedes dormir aquí!'
  no-sleep-storm: '&cNo puedes dormir durante la tormenta!'
sounds:
  night-skipped: {}
titles:
  night-skipped: {}
