tab:
  default:
    priority: 0
    commands:
      - /server
      - /skin
blocked_command_default_actions:
  - 'message: &7[&3Tele&bServer&7] &cNo tienes permiso para usar ese comando.'
use_commands_as_whitelist: false
commands:
  - /bukkit:?
  - /bukkit:ver
  - /bukkit:version
  - /bukkit:pl
  - /bukkit:plugins
  - /bukkit:help
  - /bukkit:about
  - /ver
  - /version
  - /plugins
  - /pl
  - /minecraft:me
  - /about
  - /icanhasbukkit
custom_commands_actions:
  example1:
    commands:
      - /bungee
    actions:
      - 'message: &8[&b&lECB&8] &cYou can''t see the BungeeCord version!'
