configuration_version: v5
worlds:
  world_shops:
    plot:
      height: 62
      size: 10
      filling: stone
      floor: grass_block
      bedrock: true
      biome: minecraft:forest
      sign_material: OAK_WALL_SIGN
      auto_merge: false
      create_signs: true
    wall:
      place_top_block: true
      block: smooth_stone_slab[type=bottom]
      block_claimed: smooth_quartz_slab[type=bottom]
      filling: black_concrete
      height: 62
    road:
      width: 5
      height: 62
      block: stone_bricks
      flags: {}
    misc_spawn_unowned: false
    home:
      nonmembers: side
      default: side
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
      schematics: []
    chat:
      forced: false
      enabled: true
    economy:
      prices:
        merge: 100000
        sell: 0
        claim: 100
      use: true
    world:
      max_gen_height: 319
      max_height: 320
      gamemode: creative
      min_gen_height: -64
      min_height: -63
      border: false
    event:
      spawn:
        egg: false
        breeding: false
        custom: true
    natural_mob_spawning: false
    mob_spawner_spawning: false
    flags:
      use: '#signs'
