update_notification: true
allow_chat_while_in_conversation: false
allow_commands_while_in_conversation: false
allow_inventory_interact_while_in_conversation: true
hide_chat_while_in_conversation: false
commands_whitelist:
- /login
- /help
clickable_options: true
selectable_options: false
action_bar: false
use_empty_spaces: true
use_protocollib: false
boss_bar:
  enabled: true
  color: BLUE
  style: SEGMENTED_10
  change_progress_with_time: false
send_back_hidden_chat: false
allow_mob_damage: false
conversation_start_click_type: RIGHT_CLICK
hide_chat_while_in_conversation_type: CHAT
protocollib_selectable_options_action: SNEAK
data_auto_save_time: 600
skip_dialogue_on_npc_click: false
