# TNTRun_reloaded configuration file     #
#                                        #
# The TNTRun_reloaded plugin             #
# Based on TNTRun by Shevchikden         #
#                                        #
# TNTRun_reloaded author steve4744       #
#                                        #

configmenu:
  lore: true
onstart:
  delay: 0
onjoin:
  fillhunger: true
  fillhealth: false
disablecollisions: false
usexpbar:
  countdown: true
  timelimit: true
gamemode: SURVIVAL
parties:
  enabled: true
  usePartiesPlugin: false
ondeath:
  dropitems: true
removearrows: false
special:
  UseBossBar: true
  BossBarColor: RANDOM
  UseTitle: true
  UseScoreboard: true
  UseDoubleJumpPermissions: false
  CheckForNewVersion: true
  Metrics: true
UseRankInChat:
  groupcolormeta: false
  enabled: false
  usegroup: true
  useprefix: false
freedoublejumps:
  enabled: true
  amount: 3
fireworksonwin:
  enabled: true
  duration: 4
commandsonwin:
- effect give {PLAYER} minecraft:luck 1 0 true
- effect give {PLAYER} minecraft:unluck 1 0 true
broadcastwinlevel: 1
invitationmessage:
  enabled: false
  allowspectate: false
  excludeplayers: false
  excludeoriginator: false
menu:
  item: TNT
  pvpitem: IRON_BLOCK
  panecolor: LIGHT_BLUE
  includedisabled: false
sounds:
  invitationmessage:
    enabled: false
    sound: ENTITY_PLAYER_LEVELUP
    volume: 10
    pitch: 1.0
  arenastart:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP
    volume: 10
    pitch: 1.0
  itemselect:
    enabled: true
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1.0
  blockbreak:
    enabled: true
    sound: BLOCK_SAND_BREAK
    volume: 5
    pitch: 1.0
anticamping:
  teleporttime: 5
  enabled: true
leaderboard:
  maxentries: 10
doublejumps:
  multiplier: 1.5
  height: 0.7
items:
  doublejump:
    use: false
    material: FEATHER
    name: '&e&lDoublejump'
    slot: 0
  tracker:
    use: true
    material: COMPASS
    name: '&e&lPlayer Tracker'
    slot: 5
  vote:
    use: false
    material: DIAMOND
    name: '&b&lVotar'
    slot: 0
  info:
    use: false
    material: EMERALD
    name: '&2&lInfo'
    slot: 1
  shop:
    use: false
    material: NETHER_STAR
    name: '&a&lTienda'
    slot: 1
  stats:
    use: true
    material: PLAYER_HEAD
    name: '&2&lEstadísticas'
    slot: 4
  leave:
    use: true
    material: IRON_DOOR
    name: '&c&lSalir'
    slot: 8
  heads:
    use: true
    material: GLOWSTONE_DUST
    name: '&e&lHeadsPlus'
    slot: 4
scoreboard:
  enablelobbyscoreboard: false
  lobby:
  - '&fWelcome to the TNTRun lobby'
  - '&a '
  - '&fNumber of Arenas: %tntrun_arena_count%'
  - '&b '
  - '&fGames played: %tntrun_played%'
  - '&fGames won: %tntrun_wins%'
  - '&c '
  - '&fTNTRun_reloaded v%tntrun_version%'
  header: '&7[&c&lTNT&4&lRUN&7]'
  displaydoublejumps: true
  removefromspectators: true
  waiting:
  - '&fArena: &6&l{ARENA}'
  - '&b '
  - '&fJugadores: &a&l{PS}&7&l/&c&l{MPS}'
  - '&c '
  - '&fVotos necesarios: &6&l{VOTES}'
  - '&d '
  - '&fComenzando en: &6&l{COUNT}'
  - '&e '
  - '&fDouble Jumps: &6&l{DJ}'
  playing:
  - '&fArena: &6&l{ARENA}'
  - '&b '
  - '&fJugadores: &a&l{PS}&7&l/&c&l{MPS}'
  - '&c '
  - '&fCaídos: &a&l{LOST}'
  - '&d '
  - '&fTermina en: &c&l{LIMIT}'
  - '&e '
  - '&fDouble Jumps: &6&l{DJ}'
database: file
MySQL:
  legacyDriver: false
  host: host
  port: 12345
  name: tntrun
  table: stats
  user: root
  pass: password
  useSSL: false
  flags: allowPublicKeyRetrieval=true
signs:
  allowspectate: false
  prefix: '&7[&c&lTNT&4&lRUN&7]'
  join: '&2[Unirse]'
  status:
    disabled: '&cApagado'
    ingame: '&c&l{PS}&8/&c&l{MPS}'
    regenerating: '&6&lReiniciando...'
    waiting: '&a&l{PS}&8/&a&l{MPS}'
  blockcolour:
    disabled: ''
    ingame: ''
    starting: ''
    waiting: ''
bungeecord:
  showdefaultjoinmessage: true
  randomarena: true
  useUUID: false
  teleporttohub: true
  playorspectate: false
  enabled: false
  hub: lobby
  useMOTD: true
  stopserver: false
currency:
  prefix: ''
  suffix: ' coins'
language: es
debug: false
shop:
  enabled: true
  name: '&c&lTNT&4&lRUN &6&lSHOP'
  size: 27
  doublejump:
    maxdoublejumps: 10
  logpurchases: false
  onleave:
    removepurchase: false
  showmoneyitem: GOLD_INGOT
