join: '&7[&c&lTNT&4&lRUN&7]'
subjoin: '&6{PLAYER} &7entró a jugar!'
win: '&6&lHas ganado la partida!'
subwin: '&7Felicitaciones!'
starting: '&7[&c&lTNT&4&lRUN&7]'
substarting: '&7Comenzando en &6{COUNT}'
start: '&7[&c&lTNT&4&lRUN&7]'
substart: '&7La partida ha comenzado!'
leave: ''
subleave: ''
