Title: '&0Posibles Recompensas:'
Size: 36

Reward:
  Hide_Drained_Rewards: false
  Name: '&e%reward_name%'
  Lore:
    Default:
      - '&aProbabilidad: &o%reward_chance%%'
    Win_Limit:
      Amount:
        - '&7You can win this reward &6%user_reward_win_limit_amount_left% more times &7(of total &f%reward_win_limit_amount%&7)'
      Cooldown:
        - '&7You can win this reward again in &6%user_reward_win_limit_expire_in%'
      Drained:
        - '&cYou already won this reward, you can not win more.'
  Slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26

Content:
  page_next:
    Display:
      default:
        Item:
          Material: ARROW
          Name: '&eSiguiente'
    Slots: 35
    Type: PAGE_NEXT

  page_prev:
    Display:
      default:
        Item:
          Material: ARROW
          Name: '&aAnterior'
    Slots: '27'
    Type: PAGE_PREVIOUS

  exit:
    Display:
      default:
        Item:
          Material: STRUCTURE_VOID
          Name: '&cCerrar'
    Slots: 31
    Type: CLOSE