tab:
  default:
    priority: 0
    commands:
      - /?
      - /ayuda
      - /discord
      - /help
      - /eglow
      - /instagram
      - /login
      - /msg
      - /r
      - /reglas
      - /register
      - /rules
      - /servers
      - /survival
      - /spawn
      - /telejuegos
      - /tpaccept
      - /tpadeny
      - /unregister
      - /usm
      - /vip
  vip:
    priority: 1
    extends: default
    commands:
      - /afk
      - /nick
      - /tpa
      - /tpacancel
blocked_command_default_actions:
  - 'message: &7[&3Tele&bServer&7] &cNo tienes permiso para usar ese comando.'
use_commands_as_whitelist: true
commands:
  - /?
  - /ayuda
  - /discord
  - /help
  - /eglow
  - /instagram
  - /login
  - /msg
  - /nick
  - /r
  - /ranks
  - /rangos
  - /reglas
  - /register
  - /rules
  - /servers
  - /survival
  - /spawn
  - /telejuegos
  - /tpa
  - /tpacancel
  - /tpaccept
  - /tpadeny
  - /unregister
  - /usm
  - /vip
custom_commands_actions:
  example1:
    commands:
      - /bungee
    actions:
      - 'message: &8[&b&lECB&8] &cYou can''t see the BungeeCord version!'
