hide_locked_discoveries_name: false
locked_discoveries_item: GRAY_DYE
mysql_database:
  enabled: false
  host: localhost
  port: 3306
  username: root
  password: root
  database: database
progress_bar_placeholder:
  filled_symbol: '&a|'
  empty_symbol: '&c|'
  amount: 20
data_auto_save_time: 600
locked_discoveries_item_custom_model_data: 0
