# If this is enabled, the management task loading and prioritizing the file form of the portals will be utilized.
keep-teleport-head-axis: false
bypass-portal-permissions: true
vehicle-teleportation: true
block-creative-portal-entrance: false
creature-spawning-blacklist:
- PUFFERFISH
- TROPICAL_FISH
- DOLPHIN
use-portal-cooldown: true
join-protection: true
join-protection-cooldown: 5
portal-cooldown-duration: 5
throw-velocity: 1.35
command-tick-delay: 5
teleport-sound: ENTITY_GHAST_SHOOT
teleport-visual-effect: CLOUD
selection-visual-effect: REDSTONE
selection-visual-duration: 10
region-visual-effect: REDSTONE
region-visual-duration: 20
management-task: true
maintain-vehicle-velocity: true
maintain-entity-velocity: true
nether-portal-locations:
- example_world:world,0,80,0,0,0
- example_world_the_nether:world,0,80,0,0,0
end-portal-locations:
- example_world:world,0,80,0,0,0
- example_world_the_end:world,0,80,0,0,0
end-portal-locations-handle-death: true
titles:
  fade-in: 0
  fade-out: 0
  display-time: 5
item-transfer: true
item-teleport-delay: 2
