locale: es
debug: false
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: false
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: false
player-respawn-items: false
gived-game-start-items: []
gived-player-respawn-items: []
disable-hunger: false
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion-except:
- ''
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allow-spectator-join: false
disable-server-message:
  player-join: false
  player-leave: false
disable-flight: true
respawn-cooldown:
  enabled: true
  time: 5
stop-team-spawners-on-die: false
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
  motd:
    enabled: false
    waiting: '%name%: Waiting for players [%current%/%max%]'
    waiting_full: '%name%: Game is full [%current%/%max%]'
    running: '%name%: Game is running [%current%/%max%]'
    rebuilding: '%name%: Rebuilding...'
    disabled: '%name%: Game is disabled'
  kick-when-proxy-too-slow: true
  select-random-game: true
farmBlocks:
  enable: false
  blocks: []
scoreboard:
  enable: true
  title: §a%game%§r - %time%
  bedLost: §c✘
  anchorEmpty: §e✘
  bedExists: §a✔
  teamTitle: '%bed%%color%%team%'
title:
  enabled: true
  fadeIn: 5
  stay: 20
  fadeOut: 5
shop:
  rows: 4
  render-actual-rows: 6
  render-offset: 9
  render-header-start: 0
  render-footer-start: 45
  items-on-row: 9
  show-page-numbers: true
  inventory-type: CHEST
  citizens-enabled: false
items:
  jointeam: NETHER_STAR
  leavegame: STRUCTURE_VOID
  startgame: DIAMOND
  shopback: ARROW
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: false
  reward:
    kill: 5
    win: 20
    final-kill: 5
    bed-destroy: 0
resources:
  esmeralda:
    material: EMERALD
    color: GREEN
    name: Esmeralda
    interval: 25
    translate: resource_esmeralda
    spread: 1.0
  oro:
    material: GOLD_INGOT
    color: YELLOW
    name: Oro
    interval: 10
    translate: resource_oro
    spread: 1.0
  hierro:
    material: IRON_INGOT
    color: GRAY
    name: Hierro
    interval: 2
    translate: resource_hierro
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 10
  show-messages: true
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: true
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: true
    delay: 20
    break-time: 10
    width: 5
    height: 3
    distance: 2
    material: STONE_BRICKS
  tnt-sheep:
    speed: 0.3
    follow-range: 15.0
    max-target-distance: 32
    explosion-time: 5
  arrow-blocker:
    protection-time: 10
    delay: 15
  warp-powder:
    teleport-time: 3
    delay: 0
  magnet-shoes:
    probability: 50
  golem:
    speed: 0.25
    follow-range: 10
    health: 50
    name-format: '%teamcolor%§lGolem %team%'
    show-name: true
    delay: 15
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
  throwable-fireball:
    explosion: 3.0
    damage: 2.0
    incendiary: true
    damage-thrower: true
  auto-igniteable-tnt:
    explosion-time: 8
    damage-placer: true
    damage: 4.0
  dont-show-success-messages: false
sounds:
  bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  my_bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  countdown:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  game_start:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  team_kill:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  player_kill:
    sound: ENTITY_PLAYER_BIG_FALL
    volume: 1
    pitch: 1
  item_buy:
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 1
  upgrade_buy:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1
    pitch: 1
  respawn_cooldown_wait:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  respawn_cooldown_done:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        ALPHA: 255
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: true
  title: §6§lBED§c§lWARS
  content:
  - ' '
  - '§fMapa: §2%arena%'
  - '§fJugadores: §2%players%§f/§2%maxplayers%'
  - ' '
  - §fEsperando...
  - ' '
statistics:
  enabled: true
  type: yaml
  show-on-game-end: false
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: -1
    win: 50
    bed-destroy: 25
    lose: 5
    record: 100
    final-kill: 0
database:
  host: localhost
  port: 3306
  db: databse
  user: root
  password: secret
  table-prefix: bw_
  useSSL: false
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: PURPLE
    style: SEGMENTED_20
  game:
    enable: true
    color: BLUE
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: §eEstadísticas de §6§lBed§c§lWars
  leaderboard:
    headline: '&6Bedwars Leaderboard'
    format: '&l%order%. &7%name% - &a%score%'
    size: 10
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  separate-chat:
    lobby: true
    game: true
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '!'
  team-chat-prefix: '@'
  all-chat: '§7[§aGlobal§7] '
  team-chat: '§7[§6Team§7] '
  death-chat: '§7[§8Spec§7] '
  disable-all-chat-for-spectators: false
rewards:
  enabled: true
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /serveritem give esmeralda 5 {player} true
  player-kill:
  - /serveritem give hierro 32 {player} true
  - /serveritem give oro 16 {player} true
  player-final-kill:
  - /example {player} 10
  player-win-run-immediately:
  - /example {player} 200
lore:
  generate-automatically: true
  text:
  - '§7Precio: §7%price% %resource%'
  - '§7Cantidad: §7%amount%'
sign:
  lines:
  - §7§l[§6§lBed§c§lWars§7§l]
  - '%arena%'
  - '%status%'
  - '%players%'
  block-behind:
    enabled: true
    waiting: LIME_CONCRETE
    rebuilding: RED_TERRACOTTA
    in-game: ORANGE_CONCRETE
    game-disabled: BLACK_CONCRETE
hotbar:
  selector: 0
  color: 1
  start: 4
  leave: 8
breakable:
  enabled: false
  asblacklist: false
  blocks: []
  explosions: false
leaveshortcuts:
  enabled: true
  list:
  - spawn
mainlobby:
  enabled: true
  location: 0.5;31.0;-18.5;0.0;0.0
  world: world_bedwars
turnOnExperimentalGroovyShop: false
preventSpectatorFlyingAway: true
removePurchaseMessages: true
disableCakeEating: true
disableDragonEggTeleport: true
preventArenaFromGriefing: false
update-checker:
  zero:
    console: true
    admins: true
  one:
    console: true
    admins: true
target-block:
  allow-destroying-with-explosions: false
  respawn-anchor:
    fill-on-start: true
    enable-decrease: true
    sound:
      charge: BLOCK_RESPAWN_ANCHOR_CHARGE
      used: BLOCK_GLASS_BREAK
      deplete: BLOCK_RESPAWN_ANCHOR_DEPLETE
  cake:
    destroy-by-eating: true
event-hacks:
  damage: false
  destroy: false
  place: false
default-permissions:
  join: true
  leave: true
  stats: true
  list: true
  rejoin: true
  autojoin: true
  leaderboard: true
  party: true
version: 3
allow-fake-death: false
tab:
  enable: false
  header:
    enabled: true
    contents:
    - '&aMy awesome BedWars server'
    - '&bMap: %map%'
    - '&cPlayers: %respawnable%/%max%'
  footer:
    enabled: true
    contents:
    - '&eexample.com'
    - '&fWow!!'
    - §a%spectators% are watching this match
  hide-spectators: true
  hide-foreign-players: false
enable-cheat-command-for-admins: false
shopkeepers-are-silent: true
removePurchaseFailedMessages: true
removeUpgradeMessages: true
party:
  enabled: false
  autojoin-members: false
  notify-when-warped: true
prefer-1-19-4-display-entities: true
remember-what-scoreboards-players-had-before: false
use-chunk-tickets-if-available: true
reset-full-spawner-countdown-after-picking: true
players-can-win-game-only-after-seconds: 0
kick-players-upon-final-death:
  enabled: false
  delay: 5
