Config:
  update_notification: true
  register_commands: []
  data_save_time: 5
  debug_actions: true
Messages:
  prefix: '&4[&bConditionalEvents&4] '
  commandReload: '&aConfig Reloaded.'
  commandNoPermissions: '&cNo tienes permisos para eso'
  commandResetError: '&cUse &7/ce reset <player> <event>'
  eventDoesNotExists: '&cThat event doesn''t exists on the config.'
  cooldownReset: '&aCooldown was reset for player &e%player% &aon event &e%event%&a!'
  eventEnableError: '&cUse &7/ce enable <event>'
  eventDisableError: '&cUse &7/ce disable <event>'
  eventEnabled: '&aEvent &7%event% &aenabled.'
  eventDisabled: '&aEvent &7%event% &adisabled.'
  seconds: s
  minutes: m
  hours: h
  days: d
  placeholderAPICooldownReady: Ready!
  placeholderAPICooldownNameError: No event with that name!
  eventDataResetAll: '&aAll data reset for player &e%player%&a!'
  eventDataReset: '&aData reset for player &e%player% &aon event &e%event%&a!'
  commandDebugError: '&cUse &7/ce debug <event>'
  debugEnabled: '&aDebug now enabled for event &7%event%&a!'
  debugDisabled: '&aDebug disabled for event &7%event%&a!'
  onlyPlayerCommand: '&cThis command can be only used by a player.'
  playerDoesNotExists: '&cThat player doesn''''t have any data.'
  debugEnabledPlayer: '&aDebug now enabled for event &7%event% &aand player &7%player%&a!'
  debugDisabledPlayer: '&aDebug disabled for event &7%event% &aand player &7%player%&a!'
  eventDataResetForAllPlayers: '&aData reset for &eall players &aon event &e%event%&a!'
  eventDataResetAllForAllPlayers: '&aAll player data reset.'
  commandCallError: '&cUse &7/ce call <event> (optional)%variable1%=<value1>;%variableN%=<valueN>'
  commandCallInvalidEvent: '&cYou can only execute a CALL event.'
  commandCallCorrect: '&aEvent &7%event% &asuccessfully executed.'
  commandCallFailed: '&cEvent &7%event% &ccould not be executed. Maybe a format error?'
  playerNotOnline: '&cThat player is not online.'
Events:
  atm:
    type: block_interact
    conditions:
    - '%block_x% == -61'
    - '%block_y% == 33'
    - '%block_z% == 67'
    - '%block_world% equals world'
    - '%block% equals BARRIER'
    - '%action_type% equals RIGHT_CLICK'
    - '%item_name% equals Tarjeta Cuenta RUT'
    actions:
      default:
      - 'console_command: cp panel-2 %player%'
  world_swap:
    type: item_interact
    conditions:
    - '%item% equals DIAMOND'
    - '%item_name% equals World-Swap'
    - '%action_type% equals RIGHT_CLICK'
    - '%player_world% equals world execute actions1'
    - '%player_world% equals world_planos execute actions2'
    actions:
      actions1:
      - 'console_command: mvtp %player% world_planos'
      actions2:
      - 'console_command: mvtp %player% world'
  cancel_craft:
    type: item_craft
    conditions:
    - '%item% equals GOLD_BLOCK'
    actions:
      default:
      - 'cancel_event: true'
  cancel_craft2:
    type: item_craft
    conditions:
    - '%item% equals GOLD_INGOT'
    - '%item_name% !contains $'
    actions:
      default:
      - 'cancel_event: true'
  vuelo:
    type: item_interact
    conditions:
    - '%item% equals FEATHER'
    - '%item_name% equals Vuelo'
    - '%action_type% equals RIGHT_CLICK'
    actions:
      default:
      - 'console_command: fly %player%'
  check_credential:
    type: custom
    custom_event_data:
      event: net.raidstone.wgevents.events.RegionEnteredEvent
      variables_to_capture:
      - '%region%;getRegionName()'
      player_variable: getPlayer()
    enable: false
    conditions:
    - '%region% equals porton'
    - '%checkitem_material:paper,inhand:main,namecontains:Credencial% equals no'
    actions:
      default:
      - 'cancel_event: true'
      - 'message: &cPor favor muestra tu Credencial USM'
  kit:
    type: player_join
    conditions:
    - '%objective_score_kitinicio% != 1'
    actions:
      default:
      - 'console_command: kit give Inicio %player%'
      - 'console_command: scoreboard players set %player% kitinicio 1'
  filter_msg:
    type: protocollib_receive_message
    conditions:
    - '%normal_message% contains &c&lHey! execute actions_for_all'
    - '%normal_message% contains &6Teletransportando... execute actions_for_all'
    - '%normal_message% contains &aPanel Opened for execute actions_for_all'
    - '%normal_message% contains set completed execute actions_for_all'
    actions:
      actions_for_all:
      - 'cancel_event: true'
  door_interact_closed:
    type: entity_interact
    conditions:
    - '%entity% == INTERACTION'
    - '%entity_name% == DoorInteract'
    - '%servervariables_globalvalue_glass_door% == close'
    - '%player_yaw% < 90 and %player_yaw% > -90 execute actions1'
    - '%player_yaw% < -90 or %player_yaw% < 180  execute actions2'
    actions:
      actions1:
      - 'console_command: ce enable door_interact_opened'
      - 'console_command: svar set glass_door open'
      - 'console_command: fill -32 32 52 -32 34 52 minecraft:air'
      - 'console_command: fill -31 32 53 -31 34 53 minecraft:chain[axis=z]'
      - 'console_command: minecraft:tp @e[tag=DoorInteract] -30.65 33.1 53.7'
      - 'console_command: data merge entity @e[type=item_display,limit=1,tag=GlassDoor]
        {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0.000f,0.707f,0.000f,0.707f],scale:[0.94f,1f,1f]}}'
      actions2:
      - 'console_command: ce enable door_interact_opened'
      - 'console_command: svar set glass_door open2'
      - 'console_command: fill -32 32 52 -32 34 52 minecraft:air'
      - 'console_command: fill -31 32 51 -31 34 51 minecraft:chain[axis=z]'
      - 'console_command: minecraft:tp @e[tag=DoorInteract] -30.65 33.1 51.3'
      - 'console_command: data merge entity @e[type=item_display,limit=1,tag=GlassDoor]
        {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0.000f,-0.707f,0.000f,0.707f],scale:[0.94f,1f,1f]}}'
  door_interact_opened:
    type: entity_interact
    conditions:
    - '%entity% == INTERACTION'
    - '%entity_name% == DoorInteract'
    - '%servervariables_globalvalue_glass_door% == open execute actions1'
    - '%servervariables_globalvalue_glass_door% == open2 execute actions2'
    actions:
      actions1:
      - 'console_command: ce disable door_interact_opened'
      - 'console_command: svar set glass_door close'
      - 'console_command: fill -32 32 52 -32 34 52 minecraft:chain[axis=x]'
      - 'console_command: fill -31 32 53 -31 34 53 minecraft:air'
      - 'console_command: minecraft:tp @e[tag=DoorInteract] -31.8 33.1 52.5'
      - 'console_command: data merge entity @e[type=item_display,limit=1,tag=GlassDoor]
        {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0.000f,0.000f,0.000f,1.000f],scale:[0.94f,1f,1f]}}'
      actions2:
      - 'console_command: ce disable door_interact_opened'
      - 'console_command: svar set glass_door close'
      - 'console_command: fill -32 32 52 -32 34 52 minecraft:chain[axis=x]'
      - 'console_command: fill -31 32 51 -31 34 51 minecraft:air'
      - 'console_command: minecraft:tp @e[tag=DoorInteract] -31.8 33.1 52.5'
      - 'console_command: data merge entity @e[type=item_display,limit=1,tag=GlassDoor]
        {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0.000f,0.000f,0.000f,1.000f],scale:[0.94f,1f,1f]}}'
    enabled: false
  door_interact_closed2:
    type: entity_interact
    conditions:
    - '%entity% == INTERACTION'
    - '%entity_name% == DoorInteract2'
    - '%servervariables_globalvalue_glass_door2% == close'
    - '%player_yaw% < 90 and %player_yaw% > -90 execute actions1'
    - '%player_yaw% < -90 or %player_yaw% < 180  execute actions2'
    actions:
      actions1:
      - 'console_command: ce enable door_interact_opened2'
      - 'console_command: svar set glass_door2 open'
      - 'console_command: fill -33 32 52 -33 34 52 minecraft:air'
      - 'console_command: fill -34 32 53 -34 34 53 minecraft:chain[axis=z]'
      - 'console_command: minecraft:tp @e[tag=DoorInteract2] -33.4 33.1 53.7'
      - 'console_command: data merge entity @e[type=item_display,limit=1,tag=GlassDoor2]
        {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0.000f,-0.707f,0.000f,0.707f],scale:[0.94f,1f,1f]}}'
      actions2:
      - 'console_command: ce enable door_interact_opened2'
      - 'console_command: svar set glass_door2 open2'
      - 'console_command: fill -33 32 52 -33 34 52 minecraft:air'
      - 'console_command: fill -34 32 51 -34 34 51 minecraft:chain[axis=z]'
      - 'console_command: minecraft:tp @e[tag=DoorInteract2] -33.4 33.1 51.3'
      - 'console_command: data merge entity @e[type=item_display,limit=1,tag=GlassDoor2]
        {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0.000f,0.707f,0.000f,0.707f],scale:[0.94f,1f,1f]}}'
  door_interact_opened2:
    type: entity_interact
    conditions:
    - '%entity% == INTERACTION'
    - '%entity_name% == DoorInteract2'
    - '%servervariables_globalvalue_glass_door2% == open execute actions1'
    - '%servervariables_globalvalue_glass_door2% == open2 execute actions2'
    actions:
      actions1:
      - 'console_command: ce disable door_interact_opened2'
      - 'console_command: svar set glass_door2 close'
      - 'console_command: fill -33 32 52 -33 34 52 minecraft:chain[axis=x]'
      - 'console_command: fill -34 32 53 -34 34 53 minecraft:air'
      - 'console_command: minecraft:tp @e[tag=DoorInteract2] -32.25 33.1 52.5'
      - 'console_command: data merge entity @e[type=item_display,limit=1,tag=GlassDoor2]
        {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0.000f,0.000f,0.000f,1.000f],scale:[0.94f,1f,1f]}}'
      actions2:
      - 'console_command: ce disable door_interact_opened2'
      - 'console_command: svar set glass_door2 close'
      - 'console_command: fill -33 32 52 -33 34 52 minecraft:chain[axis=x]'
      - 'console_command: fill -34 32 51 -34 34 51 minecraft:air'
      - 'console_command: minecraft:tp @e[tag=DoorInteract2] -32.25 33.1 52.5'
      - 'console_command: data merge entity @e[type=item_display,limit=1,tag=GlassDoor2]
        {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0.000f,0.000f,0.000f,1.000f],scale:[0.94f,1f,1f]}}'
    enabled: false
