tab:
  default:
    priority: 0
    commands:
      - /?
      - /ayuda
      - /cc
      - /codex
      - /createhome
      - /daily
      - /delhome
      - /delhome
      - /dinero
      - /discord
      - /events
      - /help
      - /home
      - /homes
      - /instagram
      - /jobs
      - /kits
      - /lobby
      - /money
      - /msg
      - /pay
      - /present
      - /ps
      - /quest
      - /quests
      - /r
      - /ranks
      - /rangos
      - /recipes
      - /reglas
      - /rules
      - /sell
      - /servers
      - /sethome
      - /shop
      - /shops
      - /skin
      - /spawn
      - /stats
      - /team
      - /telejuegos
      - /tpaccept
      - /tpacancel
      - /trade
      - /usm
      - /vip
      - /warp
      - /warpinfo
      - /warps
      - /halloween
  vip:
    priority: 1
    extends: default
    commands:
      - /afk
      - /nick
      - /tpa
      - /tpacancel
blocked_command_default_actions:
  - 'message: &7[&3Tele&bServer&7] &cNo tienes permiso para usar ese comando.'
use_commands_as_whitelist: true
commands:
  - /?
  - /ayuda
  - /cc
  - /codex
  - /createhome
  - /daily
  - /delhome
  - /delhome
  - /dinero
  - /discord
  - /events
  - /help
  - /home
  - /homes
  - /instagram
  - /jobs
  - /kits
  - /lobby
  - /money
  - /msg
  - /pay
  - /present
  - /ps
  - /quest
  - /quests
  - /r
  - /ranks
  - /rangos
  - /recipes
  - /reglas
  - /rules
  - /sell
  - /servers
  - /sethome
  - /shop
  - /shops
  - /skin
  - /spawn
  - /stats
  - /team
  - /telejuegos
  - /tpa
  - /tpacancel
  - /tpaccept
  - /tpadeny
  - /trade
  - /usm
  - /vip
  - /warp
  - /warpinfo
  - /warps
  - /halloween
custom_commands_actions:
  example1:
    commands:
      - /bungee
    actions:
      - 'message: &8[&b&lECB&8] &cYou can''t see the BungeeCord version!'
